CREATE TABLE prioridad (
    id SERIAL PRIMARY KEY,
    titulo VARCHAR(50) NOT NULL,
    activado BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
